spring:
  application:
    name: tm-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: As_123456

server:
  port: 7001

mybatis:
  mapper-locations: classpath*:com/taiping/tm/persistence/mapper/*.xml
  type-aliases-package: com.taiping.tm.persistence.domain

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

