spring:
  application:
    name: tm-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: As_123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

server:
  port: 7005

mybatis:
  mapper-locations: classpath*:com/taiping/tm/external/persistence/mapper/*.xml
  type-aliases-package: com.taiping.tm.external.persistence.domain

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/